name: SVG Optimization Workflow

on:
  push:
    paths:
      - '**.svg'
    branches: [ main, master ]
  pull_request:
    paths:
      - '**.svg'
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  optimize-svgs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # استفاده از جدیدترین نسخه پایدار Node.js

      - name: Install dependencies
        run: npm install -g svgo

      # به جای نوشتن اسکریپت پیچیده، از ابزارهای خط فرمان استفاده می‌کنیم
      - name: Find SVG files
        id: find-svgs
        run: |
          echo "SVG_FILES=$(find . -type f -name "*.svg" | grep -v "\.optimized\.svg" | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Optimize SVG files with SVGO
        run: |
          for file in $SVG_FILES; do
            echo "Processing $file"
            output_file="${file%.svg}.optimized.svg"
            
            # اجرای SVGO برای بهینه‌سازی پایه
            svgo --config '{
              "plugins": [
                { "removeViewBox": false },
                { "removeDimensions": true },
                { "cleanupAttrs": true },
                { "collapseGroups": true },
                { "removeUselessStrokeAndFill": true },
                { "removeEmptyAttrs": true },
                { "removeEmptyContainers": true },
                { "convertStyleToAttrs": true },
                { "removeComments": true },
                { "removeMetadata": true },
                { "removeTitle": true },
                { "removeDesc": true }
              ]
            }' -i "$file" -o "$output_file"
            
            # اضافه کردن ویژگی‌های دسترسی‌پذیری با استفاده از sed
            filename=$(basename "$file" .svg)
            tags=$(echo "$filename" | tr '-' ' ')
            
            # اضافه کردن role="img" به تگ svg
            sed -i 's/<svg/<svg role="img"/g' "$output_file"
            
            # اضافه کردن عنوان و توضیحات
            sed -i "s/<svg role=\"img\"/<svg role=\"img\">\n  <title xml:lang=\"fa\">آیکون $tags<\/title>\n  <title xml:lang=\"en\">$tags Icon<\/title>\n  <desc xml:lang=\"fa\">این آیکون برای $tags در سایت کوشک کنکور هنر استفاده می‌شود<\/desc>\n  <desc xml:lang=\"en\">This icon is used for $tags in KKArt website<\/desc/g" "$output_file"
            
            # تبدیل fill به currentColor
            sed -i 's/fill="#[0-9a-fA-F]\{3,6\}"/fill="currentColor"/g' "$output_file"
            
            echo "Optimized SVG saved to $output_file"
          done

      - name: Commit optimized SVGs
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add "*.optimized.svg" || echo "No optimized SVGs to add"
          git diff --quiet && git diff --staged --quiet || git commit -m "Optimize SVG files" -a || echo "No changes to commit"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
